#!/bin/sh

esc() {
    case $1 in
        CUU) e="${esc_c}[${2}A" ;;
        CUD) e="${esc_c}[${2}B" ;;
        CUF) e="${esc_c}[${2}C" ;;
        CUB) e="${esc_c}[${2}D" ;;
        SGR)
            case ${PF_COLOR:=1} in
                (1) e="${esc_c}[${2}m" ;;
                (0) e= ;;
            esac
        ;;
        DECAWM)
            case $TERM in
                (dumb|minix|cons25) e= ;;
                (*) e="${esc_c}[?7${2}" ;;
            esac
        ;;
    esac
}

esc_p() {
    esc "$@"
    printf '%s' "$e"
}

has() {
    _cmd=$(command -v "$1") 2>/dev/null || return 1
    [ -x "$_cmd" ] || return 1
}

log() {
    [ "$2" ] || return

    name=$1
    use_seperator=$3

    # shellcheck disable=2046,2086
    {
        set -f
        set +f -- $2
        info=$*
    }

    esc_p CUF "$ascii_width"
    esc_p SGR "3${PF_COL1-4}"
    esc_p SGR 1
    printf '%s' "$name"
    esc_p SGR 0

    [ "$use_seperator" ] || printf %s "$PF_SEP"

    esc_p CUB "${#name}"
    esc_p CUF "${PF_ALIGN:-$info_length}"

    esc_p SGR "3${PF_COL2-9}"
    printf '%s' "$info"
    esc_p SGR 0
    printf '\n'

    info_height=$((${info_height:-0} + 1))
}

get_title() {
    user=${USER:-$(id -un)}

    # shellcheck disable=3028,2039
    hostname=${HOSTNAME:-${hostname:-$(hostname)}}
    [ "$hostname" ] || read -r hostname < /etc/hostname

    esc SGR 1
    user=$e$user
    esc SGR "3${PF_COL3:-1}"
    user=$e$user
    esc SGR 1
    user=$user$e
    esc SGR 1
    hostname=$e$hostname
    esc SGR "3${PF_COL3:-1}"
    hostname=$e$hostname

    log "${user}@${hostname}" " " " " >&6
}

get_os() {
    [ "$distro" ] && {
        log os "$distro" >&6
        return
    }

    case $os in
        (Linux*)
            if has lsb_release; then
                distro=$(lsb_release -sd)
            elif [ -d /system/app ] && [ -d /system/priv-app ]; then
                distro="Android $(getprop ro.build.version.release)"
            elif [ -f /etc/os-release ]; then
                while IFS='=' read -r key val; do
                    case $key in
                        (PRETTY_NAME) distro=$val ;;
                    esac
                done < /etc/os-release
            fi

            distro=${distro##[\"\']}
            distro=${distro%%[\"\']}

            case $PATH in
                (*/bedrock/cross/*) distro='Bedrock Linux' ;;
            esac

            if [ "$WSLENV" ]; then
                distro="${distro}${WSLENV+ on Windows 10 [WSL2]}"
            elif [ -z "${kernel%%*-Microsoft}" ]; then
                distro="$distro on Windows 10 [WSL1]"
            fi
        ;;

        (*) distro="$os $kernel" ;;
    esac
}

get_kernel() {
    log kernel "$kernel" >&6
}

get_host() {
    case $os in
        (Linux*)
            read -r name    < /sys/devices/virtual/dmi/id/product_name 2>/dev/null
            read -r version < /sys/devices/virtual/dmi/id/product_version 2>/dev/null
            read -r model   < /sys/firmware/devicetree/base/model 2>/dev/null
            host="$name $version $model"
        ;;
    esac

    # shellcheck disable=2046,2086
    {
        set -f
        set +f -- $host
        host=
    }

    for word do
        case $word in
            (To|[Bb]e|[Ff]illed|[Bb]y|O.E.M.|OEM|\
            Not|Applicable|Specified|System|Product|Name|\
            Version|Undefined|Default|string|INVALID|os|\
            Type1ProductConfigId)
                continue
            ;;
        esac
        host="$host$word "
    done

    log host "${host:-$arch}" >&6
}

get_uptime() {
    case $os in
        (Linux*)
            IFS=. read -r s _ < /proc/uptime
        ;;
    esac

    d=$((s / 60 / 60 / 24))
    h=$((s / 60 / 60 % 24))
    m=$((s / 60 % 60))

    case "$d" in ([!0]*) uptime="${uptime}${d}d "; esac
    case "$h" in ([!0]*) uptime="${uptime}${h}h "; esac
    case "$m" in ([!0]*) uptime="${uptime}${m}m "; esac

    log uptime "${uptime:-0m}" >&6
}

get_pkgs() {
    packages=$(
        case $os in
            (Linux*)
                has pacman-key && pacman -Qq
                has dpkg       && dpkg-query -f '.\n' -W
                has rpm        && rpm -qa
                has xbps-query && xbps-query -l
                has apk        && apk info
                has emerge     && printf '%s\n' /var/db/pkg/*/*/
                has nix-store  && {
                    nix-store -q --requisites /run/current-system/sw
                    nix-store -q --requisites ~/.nix-profile
                }
            ;;
        esac | wc -l
    )

    packages=${packages#"${packages%%[![:space:]]*}"}
    packages=${packages%"${packages##*[![:space:]]}"}

    case $packages in
        (1?*|[2-9]*) log pkgs "$packages" >&6 ;;
    esac
}

get_memory() {
    case $os in
        (Linux*)
            while IFS=':k ' read -r key val _; do
                case $key in
                    (MemTotal)     mem_full=$val ;;
                    (MemFree)      mem_free=$val ;;
                    (Buffers)      mem_buf=$val ;;
                    (Cached)       mem_cache=$val ;;
                    (SReclaimable) mem_srec=$val ;;
                esac
            done < /proc/meminfo

            mem_used=$(((mem_full - ${mem_free:-0} - ${mem_buf:-0} - ${mem_cache:-0} - ${mem_srec:-0}) / 1024))

            mem_full=$((mem_full / 1024))
        ;;
    esac

    log memory "${mem_used:-?}M / ${mem_full:-?}M" >&6
}

get_wm() {
    # PF_WM environment variable overrides detection
    [ "$PF_WM" ] && {
        log wm "$PF_WM" >&6
        return
    }

    [ "$DISPLAY" ] || [ "$WAYLAND_DISPLAY" ] || return

    if [ "$WAYLAND_DISPLAY" ]; then
        # Wayland: check known compositor env vars first
        case ${XDG_CURRENT_DESKTOP:-} in
            (sway|Sway)       wm=sway ;;
            (Hyprland)        wm=Hyprland ;;
            (*) ;;
        esac

        [ "$wm" ] || {
            while read -r ps_line; do
                case $ps_line in
                    (*sway*)      wm=sway ;;
                    (*hyprland*)  wm=Hyprland ;;
                    (*river*)     wm=river ;;
                    (*wayfire*)   wm=wayfire ;;
                    (*labwc*)     wm=labwc ;;
                    (*cage*)      wm=cage ;;
                    (*dwl*)       wm=dwl ;;
                esac
            done <<-EOF
				$(ps x 2>/dev/null)
			EOF
        }
    fi

    [ "$wm" ] || {
        has xprop && [ "$DISPLAY" ] && {
            id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK 2>/dev/null)
            id=${id##* }

            [ "$id" ] && {
                wm=$(xprop -id "$id" -notype -len 25 -f _NET_WM_NAME 8t 2>/dev/null)

                case $wm in
                    (*'_NET_WM_NAME = '*)
                        wm=${wm##*_NET_WM_NAME = \"}
                        wm=${wm%%\"*}
                    ;;
                    (*) wm= ;;
                esac
            }
        }

        [ "$wm" ] || {
            while read -r ps_line; do
                case $ps_line in
                    (*catwm*)     wm=catwm ;;
                    (*fvwm*)      wm=fvwm ;;
                    (*dwm*)       wm=dwm ;;
                    (*2bwm*)      wm=2bwm ;;
                    (*monsterwm*) wm=monsterwm ;;
                    (*wmaker*)    wm='Window Maker' ;;
                    (*sowm*)      wm=sowm ;;
                    (*penrose*)   wm=penrose ;;
                    (*bspwm*)     wm=bspwm ;;
                    (*i3*)        wm=i3 ;;
                    (*openbox*)   wm=openbox ;;
                    (*awesome*)   wm=awesome ;;
                    (*herbstluftwm*) wm=herbstluftwm ;;
                esac
            done <<-EOF
				$(ps x 2>/dev/null)
			EOF
        }
    }

    log wm "$wm" >&6
}

get_de() {
    log de "${XDG_CURRENT_DESKTOP:-$DESKTOP_SESSION}" >&6
}

get_shell() {
    log shell "${SHELL##*/}" >&6
}

get_editor() {
    editor=${VISUAL:-"$EDITOR"}
    log editor "${editor##*/}" >&6
}

get_palette() {
    # shellcheck disable=2154
    {
        esc SGR 7
        palette="$e$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 "
        esc SGR 0
        palette="$palette$e"
    }

    printf '\n' >&6
    log "$palette
        " " " " " >&6
}

get_ascii() {
    read_ascii() {
        PF_COL1=${PF_COL1:-${1:-7}}
        PF_COL3=${PF_COL3:-$((${1:-7}%8+1))}

        while IFS= read -r line; do
            ascii="$ascii$line
"
        done
    }

    # shellcheck disable=2154
    read_ascii 4 <<-EOF
		${c4}    ___
		   ${c4}(${c7}.. ${c4}|
		   ${c4}(${c5}<> ${c4}|
		  ${c4}/ ${c7}__  ${c4}\\
		 ${c4}( ${c7}/  \\ ${c4}/|
		${c5}_${c4}/\\ ${c7}__)${c4}/${c5}_${c4})
		${c5}\/${c4}-____${c5}\/
	EOF

    while read -r line; do
        ascii_height=$((${ascii_height:-0} + 1))
        [ "${#line}" -gt "${ascii_width:-0}" ] &&
            ascii_width=${#line}
    done <<-EOF
		$(printf %s "$ascii" | sed 's/\[3.m//g')
	EOF

    ascii_width=$((ascii_width + 4))

    {
        esc_p SGR 1
        printf '%s' "$ascii"
        esc_p SGR 0
        esc_p CUU "$ascii_height"
    } >&6
}

main() {
    case $* in
        -v) printf '%s 0.1.0\n' "${0##*/}"; return 0 ;;
        -d) ;;
        '') exec 2>/dev/null ;;
        *)
            printf '%s     show system information\n' "${0##*/}"
            printf '%s -d  show stderr (debug mode)\n' "${0##*/}"
            printf '%s -v  show version information\n' "${0##*/}"
            return 0
        ;;
    esac

    exec 6>&1 >/dev/null

    esc_c=$(printf '\033')

    ! [ -f "$PF_SOURCE" ] || . "$PF_SOURCE"

    [ -w "${TMPDIR:-/tmp}" ] || export TMPDIR=~

    # shellcheck disable=2034
    for _c in c1 c2 c3 c4 c5 c6 c7 c8; do
        esc SGR "3${_c#?}" 0
        export "$_c=$e"
    done

    esc_p DECAWM l >&6
    trap 'esc_p DECAWM h >&6' EXIT

    read -r os kernel arch <<-EOF
		$(uname -srm)
	EOF

    get_os

    # shellcheck disable=2086
    {
        set -f
        set +f -- ${PF_INFO-ascii title os host kernel uptime pkgs memory wm}

        for info do
            command -v "get_$info" >/dev/null || continue
            [ "${#info}" -gt "${info_length:-0}" ] &&
                info_length=${#info}
        done

        info_length=$((info_length + 1))

        for info do
            "get_$info"
        done
    }

    [ "${info_height:-0}" -lt "${ascii_height:-0}" ] &&
        cursor_pos=$((ascii_height - info_height))

    while [ "${i:=0}" -le "${cursor_pos:-0}" ]; do
        printf '\n'
        i=$((i + 1))
    done >&6
}

main "$@"
